public class ASPNotifiableCaseAttributes {
    public String authId {get; set;}
	public String occurenceDesc {get; set;}
    public String contFact {get; set;}
    public String followDesc {get; set;}
    public String accId {get; set;}
    public String contactId {get; set;}
    public String streetadd {get; set;}
    public String cityadd {get; set;}
    public String stateadd {get; set;}
    public String postCodeadd {get; set;}
    public DateTime no_date {get; set;}
    public DateTime no_Became_Aware_Date_Time {get; set;}
    public Boolean a {get; set;}
    public Boolean b {get; set;}
    public Boolean c {get; set;}
    public Boolean d {get; set;}
    public Boolean e {get; set;}
    public String contactName {get; set;}
    public String accountName {get; set;}
    public String geoLatitude {get; set;}
    public String geoLongitude {get; set;}
    public String CovidNO {get; set;}
    public ASPNotifiableCaseAttributes(){
    }
}