public class P2POSRPaymentStatus {
    
    public String TfNSWProviderNumber { get; set; }
    public String regnType { get; set; }
    public String levyAssessmentID { get; set; }
    public String OSRAssessmentNumber { get; set; }
    public Decimal amountCollected { get; set; }
    public String reportDate { get; set; }    
    public String receiptId { get; set; }
    public String failureReason { get; set; }
    
}