/**
 * Constants, Enums in WIBS API
 */
public class P2PWIBSConstants {
	
    /** HTTP Response Status Codes */
    public static final Integer                  HTTP_OK = 200;
    public static final Integer            HTTP_ACCEPTED = 202;
    public static final Integer          HTTP_NO_CONTENT = 204;
    public static final Integer         HTTP_BAD_REQUEST = 400;
    public static final Integer           HTTP_FORBIDDEN = 403;
    public static final Integer           HTTP_NOT_FOUND = 404;
    public static final Integer        HTTP_SERVER_ERROR = 500;
    public static final Integer HTTP_SERVICE_UNAVAILABLE = 503;
    
    /** Westpac QuickWeb Summary Response Codes */
    public static final Integer QUICKWEB_CC_APPROVED = 0;
    public static final Integer QUICKWEB_CC_DECLINED = 0;
    public static final Integer    QUICKWEB_CC_ERROR = 0;
    public static final Integer QUICKWEB_CC_REJECTED = 0;
    
    
}